import Head from "next/head";
import Image from "next/image";
import MainPage from "../components";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <span className={`${styles.tags} ${styles.top__tags}`}>
          &lt;body&gt;
        </span>
        <MainPage />
        <span className={`${styles.tags} ${styles.bottom__tags}`}>
          &lt;/body&gt;
          <br />
          <span className={styles.bottom__tag__html}>&lt;/html&gt;</span>
        </span>
      </main>
    </div>
  );
}
